modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="Better Compatibility Checker" #mandatory
authors="${mod_author}" #optional
description='''
A better compatibility checker for Minecraft.
'''