name: Build & Snapshot

on:
  push:
    branches:
      - "*"

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: nanite/workflows/.github/workflows/base-java.yml@main
    secrets:
      nanite-token: ${{ secrets.NANITE_DEPLOY }}
    with:
      java-version: 21
      use-snapshots: true
      gradle-tasks: build publish